import json
from pathlib import Path

def load_chunks(json_path):
    """
    Load previously generated chunks from JSON.

    We do NOT parse the SRT again.

    Step 7 has already completed:
        SRT → chunks

    Step 8 starts from:
        chunks.json
    """

    with json_path.open(
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    return data

def create_document(chunk):
    """
    Convert one RAG chunk into a Document-like structure.

    page_content:
        Text that will eventually be embedded.

    metadata:
        Information we want to preserve alongside
        the vector.
    """

    document = {

        "page_content": chunk["text"],

        "metadata": {

            "chunk_id": chunk["chunk_id"],

            "source_file": chunk["source_file"],

            "start": chunk["start"],

            "end": chunk["end"],

            "start_seconds": chunk["start_seconds"],

            "end_seconds": chunk["end_seconds"],

            "subtitle_start": chunk["subtitle_start"],

            "subtitle_end": chunk["subtitle_end"],

            "token_count": chunk["token_count"]
        }
    }

    return document

def main():

    # -----------------------------------------------------
    # Input JSON generated by Step 7
    # -----------------------------------------------------

    input_path = Path(
        "output/chunks.json"
    )


    # -----------------------------------------------------
    # Verify input file
    # -----------------------------------------------------

    if not input_path.exists():

        print(
            f"File not found: {input_path}"
        )

        return


    # -----------------------------------------------------
    # Load chunks
    # -----------------------------------------------------

    data = load_chunks(
        input_path
    )


    chunks = data["chunks"]


    print(
        f"Chunks loaded: {len(chunks)}"
    )


    # -----------------------------------------------------
    # Convert chunks → documents
    # -----------------------------------------------------

    documents = []


    for chunk in chunks:

        document = create_document(
            chunk
        )

        documents.append(
            document
        )


    print(
        f"Documents created: {len(documents)}"
    )


    # -----------------------------------------------------
    # Display first document
    # -----------------------------------------------------

    print("\n")
    print("=" * 60)
    print("DOCUMENT 1")
    print("=" * 60)


    first_document = documents[0]


    print(
        "\nPage Content:\n"
    )

    print(
        first_document["page_content"]
    )


    print(
        "\nMetadata:\n"
    )

    print(
        first_document["metadata"]
    )


# ---------------------------------------------------------
# Entry point
# ---------------------------------------------------------

if __name__ == "__main__":
    main()    